### ISSUE TITLE
S3 Alternate providers support?

### ISSUE THREAD

**Issue by bpolaszek** [dral3x/ha-addons#4]
Hello,

Do you plan supporting alternate S3 providers, such as DigitalOcean, Scaleway etc?
Usually it takes an extra `endpoint` parameter, which generally is the URL of the bucket.

Example with PHP's `async-aws` package: https://async-aws.com/configuration.html#endpoint

Some other link that could be relevant: https://stackoverflow.com/questions/53712255/how-to-use-aws-cli-with-digital-ocean-spaces/53713795#53713795

Thanks!
Ben

**Comment by dral3x** [comment]
Hi @bpolaszek,
thanks for the suggestion!

I think it's easy enough for me to do it in the upcoming weeks.

**Comment by bpolaszek** [comment]
Oh, great! 😃 

Keep me posted! 🙏 

_PS: also if you want some DigitalOcean S3 credentials to perform tests, don't hesitate to hit me privately at my nickname at gmail dot com 👍_

**Comment by dral3x** [comment]
This is now integrated into version 1.0.2.
@bpolaszek please update your installation and let me know if it works as expected. 
Just be aware that the endpoint URL should not contain the bucket name inside (I don't know the reason, but it works only without it).

**Comment by maxime1992** [comment]
I can confirm this works perfectly. BTW thank you so much for this addon, after searching for a few days, I probably lost 4h trying to upload a backup to Minio... And this addon worked straight away :pray:! Nice one

**Comment by bpolaszek** [comment]
Hi @dral3x - sorry I forgot to come back to you ! >_<

It didn't work at first (I copy/pasted the automation in the doc and HA was not happy with it) but after managing to create the automation I can see the files in my bucket.
Thanks a lot for the good work! 👏 🙏

**Comment by dral3x** [comment]
Great! Thank you @bpolaszek for helping with testing!
